Added an example with png rounded modules using gd
chillerlan/php-qrcode pull request #215
Opened 2023-09-17 16:36 UTC by livingroot

Result: 
![](https://raw.githubusercontent.com/chillerlan/php-qrcode/3a6a4f891c99ff96de568ccdc0a61e8f02455cae/examples/imageRoundedModules.png)

Similar to:
https://github.com/chillerlan/php-qrcode/issues/127

2023-09-17 18:04 UTC, codemasher commented
Oh wow, this is incredible! Just let me have a quick look over the commit. 🚀

2023-09-17 18:30 UTC, codemasher requested changes

2023-09-17 18:30 UTC, codemasher commented on examples/imageRoundedModules.png
Can you please remove the example image from the directory? I might include a render to the documentation at some point.

2023-09-17 18:30 UTC, codemasher commented on examples/pngWithRoundedShapes.php
> +
Please add a file header with your credit and a short description perhaps:

```
/**
 * <description>
 * 
 * @see https://github.com/chillerlan/php-qrcode/issues/127
 *
 * @created      17.09.2023
 * @author       <you, e.g. GH username/profile>
 * @copyright    2023 <you>
 * @license      MIT
 */
```

2023-09-17 18:30 UTC, codemasher commented on examples/pngWithRoundedShapes.php
> +        if ($neighbours & (1 << 1)) { // neighbour сверху
i guess "сверху" means "top"

2023-09-17 18:30 UTC, codemasher commented on examples/pngWithRoundedShapes.php
> +        if ($neighbours & (1 << 5)) { // neighbour снизу
and "снизу" means "bottom" then

2023-09-17 18:30 UTC, codemasher commented on examples/pngWithRoundedShapes.php
> +            if ($neighbours & 1 && $neighbours & (1 << 7) && $neighbours & (1 << 1)) {
PHPCS will yell at this (and all other) "unbracketed operation"

The many braces but clean way would be:
```php
if (($neighbours & 1) && ($neighbours & (1 << 7)) && ($neighbours & (1 << 1))){}
```

2023-09-17 18:30 UTC, codemasher commented on examples/pngWithRoundedShapes.php
> +echo $img;
Other than the mentioned it's mostly just code formatting, but don't worry about that, I'll just run it through the formatter later to align it with the other examples

2023-09-17 19:08 UTC, codemasher commented
Also, i noticed that your branch is like 6 months behind `dev-main` - could you please update and check if it still works for you (spoiler: it probably won't and I'm currently trying to find out why).

2023-09-17 19:11 UTC, codemasher commented
Update: it's because the `setPixel()` method has ben renamed to `module()` for consistency across the several output classes.

2023-09-17 19:13 UTC, codemasher commented on examples/pngWithRoundedShapes.php
> +    protected function setPixel(int $x, int $y, int $M_TYPE): void {
The `setPixel()` method has ben renamed to `module()` in the current `dev-main`.

2023-09-17 19:17 UTC, codemasher commented on examples/pngWithRoundedShapes.php
> +            (int)(2 * $this->options->circleRadius * $this->scale),
`$this->options->circleRadius` creates some funny (probably unintended) effects when it's set to a value other than 0.5 - I think hardcoding 0.5 would be the better option here.

2023-09-18 12:38 UTC, livingroot commented
Thank you for your review, i will fix this issues. But i can't see `dev-main` branch. Did you mean `main`?

2023-09-18 12:41 UTC, codemasher commented
Yes, `main` it is - `dev-main` is the composer name - a habit of mine i guess haha.

2023-09-18 18:07 UTC, livingroot commented
All done! However, I am not sure about PHPCS complaining about single if conditions like `if ($neighbours & (1 << 3)) {`. I think it would be even worse for readability if this condition had additional brackets. Should I add them too?

2023-09-18 18:08 UTC, livingroot commented
Also, I have checked that everything is working fine

2023-09-18 18:13 UTC, codemasher commented
> All done! However, I am not sure about PHPCS complaining about single if conditions like `if ($neighbours & (1 << 3)) {`. I think it would be even worse for readability if this condition had additional brackets. Should I add them too?

I agree that this case is a bit weird, but there's no way to my knowledge to exclude these cases via the xml config. I have added them throughout the library for consistency, alternatively you can just disable the ckech for that line with a `// phpcs:ignore`.


> Also, I have checked that everything is working fine

That's great! Thank you for your contribution! 🚀

2023-09-18 18:18 UTC, codemasher approved these changes

2023-09-18 18:18 UTC, codemasher commented on examples/pngWithRoundedShapes.php
> +        $rectsize = $this->scale / 2;
This causes an "implicit conversion from float to int" exception in `imagefilledrectangle()` -> cast to int or use `intdiv()`

2023-09-18 18:18 UTC, codemasher commented on examples/pngWithRoundedShapes.php
> +
You could also intercept the constructor to enable the internal upscaling for "rounder" corners at lower scales (which would be counter-intuitive for the user to set):

```php
	public function __construct(SettingsContainerInterface $options, QRMatrix $matrix){
		$options->drawCircularModules = true;

		parent::__construct($options, $matrix);
	}
```

2023-09-18 18:19 UTC, merged